#define XDP2_DFTABLE_$TYPE$_TABLE$CLASS$_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	__XDP2_DTABLE_$TYPE$_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT$CLASS$(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC$CLASS$(NAME, KEY_DEF)			\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC(NAME, $LTYPE$)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_$TYPE$_FUNCS(			\
		NAME, struct XDP2_JOIN2(NAME, _key_struct) *)

#define XDP2_DFTABLE_$TYPE$_TABLE$CLASS$_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_FUNC, NULL,	\
		$TYPE$, $LTYPE$,					\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DFTABLE_$TYPE$_TABLE$CLASS$(NAME, KEY_ARG_TYPE,		\
					 KEY_DEF, DEFAULT_FUNC, CONFIG)	\
	XDP2_DFTABLE_$TYPE$_TABLE$CLASS$_DECL(NAME, KEY_ARG_TYPE,	\
					      KEY_DEF)			\
	XDP2_DFTABLE_$TYPE$_TABLE$CLASS$_DEFINE(NAME, DEFAULT_FUNC,	\
						CONFIG)

#define XDP2_DTABLE_$TYPE$_TABLE$CLASS$_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	__XDP2_DTABLE_$TYPE$_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_TABLES_MAKE_KEY_STRUCT$CLASS$(NAME, KEY_DEF)		\
	__XDP2_MAKE_KEY_FUNC$CLASS$(NAME, KEY_DEF)			\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC(NAME, $LTYPE$, TARG_TYPE)	\
	__XDP2_DTABLE_LOOKUP_TABLE_$TYPE$_FUNCS(NAME,			\
			struct XDP2_JOIN2(NAME, _key_struct) *, TARG_TYPE)

#define XDP2_DTABLE_$TYPE$_TABLE$CLASS$_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, $TYPE$,	\
				       $LTYPE$,				\
		struct XDP2_JOIN2(NAME, _key_struct) *, CONFIG)

#define XDP2_DTABLE_$TYPE$_TABLE$CLASS$(NAME, KEY_ARG_TYPE, KEY_DEF,	\
					TARG_TYPE, DEFAULT_TARG, CONFIG)\
	XDP2_DTABLE_$TYPE$_TABLE$CLASS$_DECL(NAME, KEY_ARG_TYPE,	\
					     KEY_DEF, TARG_TYPE)	\
	XDP2_DTABLE_$TYPE$_TABLE$CLASS$_DEFINE(NAME, DEFAULT_TARG,	\
					       CONFIG)

