#define XDP2_DFTABLE_$TYPE$_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_$TYPE$_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DFTABLE_MAKE_LOOKUP_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
					     $LTYPE$)			\
	__XDP2_DFTABLE_LOOKUP_TABLE_$TYPE$_FUNCS(NAME, KEY_ARG_TYPE)

#define XDP2_DFTABLE_$TYPE$_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)			\
	__XDP2_DFTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_ACTION,		\
		NULL, $TYPE$, $LTYPE$, XDP2_JOIN2(NAME, _key_arg_t),	\
		CONFIG)

#define XDP2_DFTABLE_$TYPE$_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       DEFAULT_ACTION, CONFIG)		\
	XDP2_DFTABLE_$TYPE$_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE)		\
	XDP2_DFTABLE_$TYPE$_TABLE_SKEY_DEFINE(NAME, DEFAULT_ACTION,	\
					      CONFIG)

#define XDP2_DTABLE_$TYPE$_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	__XDP2_DTABLE_$TYPE$_TABLE_DECL(NAME)				\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_DTABLE_MAKE_TARG_TYPEDEF(NAME, TARG_TYPE)		\
	__XDP2_DTABLE_MAKE_LOOKUP_FUNC_SKEY(				\
		NAME, KEY_ARG_TYPE, $LTYPE$, TARG_TYPE)			\
	__XDP2_DTABLE_LOOKUP_TABLE_$TYPE$_FUNCS(NAME, KEY_ARG_TYPE,	\
						TARG_TYPE)

#define XDP2_DTABLE_$TYPE$_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)			\
	__XDP2_DTABLE_MAKE_MATCH_TABLE(NAME, DEFAULT_TARG, $TYPE$,	\
				       $LTYPE$,				\
				       XDP2_JOIN2(NAME, _key_arg_t),	\
				       CONFIG)

#define XDP2_DTABLE_$TYPE$_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG, CONFIG)		\
	XDP2_DTABLE_$TYPE$_TABLE_SKEY_DECL(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE)			\
	XDP2_DTABLE_$TYPE$_TABLE_SKEY_DEFINE(NAME, DEFAULT_TARG,	\
					     CONFIG)

