#define XDP2_SFTABLE_$TYPE$_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)		\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_SFTABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), COMMON_ARGS_SIG)	\
	__XDP2_SFTABLE_MAKE_ACTIONS_TABLE(NAME, ACTIONS)		\
	__XDP2_SFTABLE_MAKE_DEFAULT_FUNC(NAME, COMMON_ARGS_SIG,		\
					 DEFAULT_ACTION)		\
	__XDP2_SFTABLE_MAKE_MATCH_TABLE(NAME, COMMON_ARGS_SIG, $LTYPE$)	\
	__XDP2_SFTABLE_MAKE_LOOKUP_$TYPE$_FUNC_SKEY(			\
		NAME, KEY_ARG_TYPE, COMMON_ARGS_SIG, COMMON_ARGS_LIST)

#define XDP2_SFTABLE_$TYPE$_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					    COMMON_ARGS_SIG,		\
					    COMMON_ARGS_LIST, ACTIONS,	\
					    DEFAULT_ACTION, ENTRIES)	\
	XDP2_SFTABLE_$TYPE$_TABLE_SKEY(NAME, KEY_ARG_TYPE,		\
				       COMMON_ARGS_SIG,			\
				       COMMON_ARGS_LIST, ACTIONS,	\
				       DEFAULT_ACTION)			\
	__XDP2_SFTABLE_MAKE_$TYPE$_MATCH_ENTRIES(NAME, ENTRIES,		\
						 COMMON_ARGS_SIG)

#define XDP2_STABLE_$TYPE$_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_DTABLE_MAKE_KEY_ARG_TYPEDEF(NAME, KEY_ARG_TYPE)		\
	__XDP2_STABLE_MAKE_TABLE_ENTRY_STRUCT(NAME,			\
			typeof(*((KEY_ARG_TYPE)0)), TARG_TYPE)		\
	__XDP2_STABLE_MAKE_MATCH_TABLE(NAME, TARG_TYPE, DEFAULT_TARG,	\
				       $LTYPE$)				\
	__XDP2_STABLE_MAKE_LOOKUP_$TYPE$_FUNC_SKEY(NAME, KEY_ARG_TYPE,	\
						   TARG_TYPE)

#define XDP2_STABLE_$TYPE$_TABLE_SKEY_ENTS(NAME, KEY_ARG_TYPE,		\
					   TARG_TYPE, DEFAULT_TARG,	\
					   ENTRIES)			\
	XDP2_STABLE_$TYPE$_TABLE_SKEY(NAME, KEY_ARG_TYPE, TARG_TYPE,	\
				      DEFAULT_TARG)			\
	__XDP2_STABLE_MAKE_$TYPE$_MATCH_ENTRIES(NAME, ENTRIES)

