include ../../config.mk

TARGETS= cli.h

INCDIR=$(INSTALLDIR)$(HDRDIR)/cli

.PHONY: all
all: $(TARGETS)

.PHONY: install
install: $(TARGETS)
	@install -m 0755 -d $(INCDIR)
	$(QUIET_INSTALL)$(INSTALL) -m 0644 $^ $(INCDIR)

.PHONY: clean
clean:
